- name : Configure Docker on EC2 Instances
  hosts : all
  become: yes
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt update

  - name : Install Docker
    command : sudo apt install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name: Deploy Docker Container
    command: docker run -itd -p 8082:8081 rocky8055/my-app:latest
